import Head from 'next/head'
import ProductItem from '../components/ProductItem'
import data from '../Utils/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextJs Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='home-page'>
        <h1 className=''>Products</h1>
        <div className='grid grid-cols-1 grap-4 md:grid-cols-3 lg:grid-cols-4'>
          {
            data.products.map((product, item) => (
              <ProductItem product={product} key={item} />
            ))
          }
        </div>
      </div>

      
    </div>
  )
}
